// Generated by CoffeeScript 1.4.0
var express = require('express')
  , http = require('http')
  , app = express()
  , server = http.createServer(app)
  , io = require('socket.io').listen(server)
  , fs = require('fs')
  , game = require('./js/game')
  , c;

c = new game.ServerController;

io.sockets.on('connection', function (socket) {
  return c.onconnect(socket);
});
server.listen(9999);