// Generated by CoffeeScript 1.4.0
var client, socket,
  _this = this;

client = require('socket.io-client');

socket = client.connect('http://localhost:9999');

socket.on("mj_action", function(a) {
  var response;
  console.log("->", a);
  switch (a.type) {
    case "start_game":
      _this.id = a.id;
      response = {
        type: "none"
      };
      break;
    case "end_game":
      response = false;
      break;
    case "tsumo":
      if (a.actor === _this.id) {
        response = {
          type: "dahai",
          actor: _this.id,
          pai: a.pai,
          tsumogiri: true
        };
      } else {
        response = {
          type: "none"
        };
      }
      break;
    case "error":
      response = false;
      break;
    default:
      response = {
        type: "none"
      };
  }
  if (response) {
    console.log("<-", response);
    return socket.emit("mj_action", response);
  }
});

socket.emit("join", {
  type: "join",
  name: "tsumogiri",
  room: "room"
});

/*c=new ServerController()
c.onconnect(new TestSocket)
c.onconnect(new TestSocket)
c.onconnect(new TestSocket)
c.onconnect(new TestSocket)
*/

